In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent


['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
## Define the vocabulary size
voc_size=10000

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7544, 3226, 3719, 880],
 [7544, 3226, 3719, 8123],
 [7544, 2715, 3719, 1195],
 [4797, 5501, 2584, 1724, 2529],
 [4797, 5501, 2584, 1724, 9665],
 [6765, 7544, 3943, 3719, 5253],
 [3752, 9964, 4791, 1724]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [18]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7544 3226 3719  880]
 [   0    0    0    0 7544 3226 3719 8123]
 [   0    0    0    0 7544 2715 3719 1195]
 [   0    0    0 4797 5501 2584 1724 2529]
 [   0    0    0 4797 5501 2584 1724 9665]
 [   0    0    0 6765 7544 3943 3719 5253]
 [   0    0    0    0 3752 9964 4791 1724]]


In [19]:
## feature representation
dim=10

In [21]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [22]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 189ms/step


array([[[ 1.37080066e-02,  1.83578394e-02, -9.68887657e-03,
          2.56197192e-02,  1.09197497e-02,  2.49833353e-02,
         -1.36636570e-03,  4.72443216e-02,  2.79606842e-02,
         -3.45790386e-02],
        [ 1.37080066e-02,  1.83578394e-02, -9.68887657e-03,
          2.56197192e-02,  1.09197497e-02,  2.49833353e-02,
         -1.36636570e-03,  4.72443216e-02,  2.79606842e-02,
         -3.45790386e-02],
        [ 1.37080066e-02,  1.83578394e-02, -9.68887657e-03,
          2.56197192e-02,  1.09197497e-02,  2.49833353e-02,
         -1.36636570e-03,  4.72443216e-02,  2.79606842e-02,
         -3.45790386e-02],
        [ 1.37080066e-02,  1.83578394e-02, -9.68887657e-03,
          2.56197192e-02,  1.09197497e-02,  2.49833353e-02,
         -1.36636570e-03,  4.72443216e-02,  2.79606842e-02,
         -3.45790386e-02],
        [ 1.26825236e-02, -2.64664739e-03,  8.22700188e-03,
         -2.98781395e-02, -6.73874468e-03,  5.74511290e-03,
          2.09025480e-02,  1.63373835e-02,  3.995041

In [24]:
embedded_docs[0]

array([   0,    0,    0,    0, 7544, 3226, 3719,  880])